{% set name = "chemplot" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemplot-{{ version }}.tar.gz
  sha256: 306b34ffa825ea63713ddeb140ad3dfdd1633c7971d1c3c9dd7bf4f936b24aeb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - rdkit
    - numpy
    - networkx
    - packaging
    - pandas
    - matplotlib
    - seaborn
    - umap-learn
    - scikit-learn
    - bokeh
    - scipy
    - mordredcommunity

test:
  imports:
    - chemplot
    - chemplot.tests
  commands:
    - python -m pytest --pyargs chemplot
  requires:
    - pytest
    - python

about:
  home: https://github.com/mcsorkun/ChemPlot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python library for chemical space visualization.
  description: |
    In the last decades, Machine Learning (ML) applications have had a great impact on molecular and 
    material science. However, every ML model requires a definition of its applicability domain. Chemplot 
    is a python library for chemical space visualization that allows users to plot the chemical space of 
    their datasets. Chemplot contains smart algorithms behind which uses both structural and tailored 
    similarity. Moreover, it is easy to use even for non-experts.
  doc_url: https://chemplot.readthedocs.io/en/latest/
  dev_url: https://github.com/mcsorkun/ChemPlot

extra:
  recipe-maintainers:
    - dajtmullaj
    - mcsorkun
    - JacksonBurns
